[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.15"
futures = "0.3"
log = "0.4"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.133"
rand = "0.8.4"
